export const projects = [
  {
    slug: "jobpilot",
    title: "JobPilot",
    description: "AI-powered job application tracker that integrates Gmail API and Claude Haiku to auto-parse emails and organize applications. React Native frontend, Node.js backend deployed on Render + Supabase.",
    liveUrl: "https://github.com/Anvians",
    repoUrl: "https://github.com/Anvians",
    tags: ["GenAI", "React Native", "Node.js", "Supabase", "Claude"],
    category: "ai",
  },
  {
    slug: "osint-crawler",
    title: "OSINT Username Crawler",
    description: "Cross-platform OSINT tool for username reconnaissance across 50+ platforms. FastAPI async backend with a clean vanilla JS frontend.",
    liveUrl: "https://portfoliotools-two.vercel.app",
    repoUrl: "https://github.com/Anvians/independent-project",
    tags: ["FastAPI", "Python", "OSINT", "Async"],
    category: "security",
  },
  {
    slug: "GitVisualizer",
    title: "GitVisualizer",
    description: "Analyze GitHub profiles with beautiful visual charts for repositories, language usage, and contribution activity statistics.",
    liveUrl: "https://gitvisualizer-anvians.vercel.app",
    repoUrl: "https://github.com/Anvians/GitVisualizer",
    tags: ["React", "Vite", "GitHub API", "Charts"],
    category: "fullstack",
  },
  {
    slug: "hiver",
    title: "Hiver — Email Classifier",
    description: "Gemini-powered email triage and classification system. Automatically categorizes inbox messages by priority and intent.",
    liveUrl: "https://hiver-anvians.vercel.app/",
    repoUrl: "https://github.com/Anvians/Hiver",
    tags: ["Gemini AI", "React", "NLP"],
    category: "ai",
  },
  {
    slug: "college-connect",
    title: "College Connect",
    description: "Full-stack campus events management platform with private social media integration and real-time notifications.",
    liveUrl: "https://campus-events-handler.vercel.app/",
    repoUrl: "https://github.com/Anvians/College-Connect",
    tags: ["React", "Node.js", "MongoDB", "Events"],
    category: "fullstack",
  },
  {
    slug: "chat-app",
    title: "CHITCHAT",
    description: "Real-time full-stack chat application featuring Socket.IO rooms, presence indicators, and message history persistence.",
    liveUrl: "https://chat-anvians.vercel.app/",
    repoUrl: "https://github.com/Anvians/Chat-App",
    tags: ["Socket.IO", "React", "Express", "MongoDB"],
    category: "fullstack",
  },
];
